version: '3.8'

services:
  app:
    build: .
    container_name: akilli-ajanda-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/akilli_ajanda_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Seyit.2003
      - FILE_UPLOAD_DIR=/app/uploads/
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads

  db:
    image: postgres:15-alpine
    container_name: akilli-ajanda-db
    environment:
      - POSTGRES_DB=akilli_ajanda_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Seyit.2003
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads_data:
